### ISSUE TITLE
Returning UPnPError 709

### ISSUE THREAD

**Issue by JohnnyUSA** [NathanaelA/minidlna#10]
Hi and thanks for your work, i really like what you did here.

First of all, your minidlna version is working fine on my Egreat Media Player but, when i try to access DLNA from my IPhone, i get some errors and no folders are shown.

```
[2018/01/21 11:46:14] minidlna.c:1028: warn: Starting MiniDLNA version 1.1.6.
[2018/01/21 11:46:14] minidlna.c:1068: warn: HTTP listening on port 8200
[2018/01/21 11:47:31] upnpsoap.c:1533: warn: SQL error: near "order": syntax error
BAD SQL: SELECT o.OBJECT_ID, 0, o.REF_ID, o.DETAIL_ID, o.CLASS, d.SIZE, d.TITLE, d.DURATION, d.BITRATE, d.SAMPLERATE, d.ARTIST, d.ALBUM, d.GENRE, d.COMMENT, d.CHANNELS, d.TRACK, d.DATE, d.RESOLUTION, d.THUMBNAIL, d.CREATOR, d.DLNA_PN, d.MIME, d.ALBUM_ART, d.ROTATION, d.DISC from OBJECTS o left join DETAILS d on (d.ID = o.DETAIL_ID) where (PARENT_ID = '64' and (o.password is null or o.password = '' or o.password in ('')) order by o.CLASS, d.TITLE)  limit 0, -1;
[2018/01/21 11:47:31] upnpsoap.c:123: warn: Returning UPnPError 709: Unsupported or invalid sort criteria
```

I'm running minidlna on an NSA310s NAS running Debian v9.

**Comment by NathanaelA** [comment]
Looks like a bug in SQL generation.   The last part is:
` (PARENT_ID = '64' and (o.password is null or o.password = '' or o.password in ('')) order by o.CLASS, d.TITLE) `

The `order by` should be outside the closing `)`

**Comment by JohnnyUSA** [comment]
Thanks for the fast reply, i'm not very tech savvy, is there a way to fix this myself? Or should i wait for you Nathanael to post a fix?

PS: From what i've seen, minidlna is detecting my IPhone as LG and looking throught the code, i've seen some LG specific patches. This could be the cause?

Thanks in advance!

PS: Updated my 1st post for a better reading experience.

**Comment by NathanaelA** [comment]
Actually I accepted a pull request yesterday that should have fixed it.   If you do another git pull; you should have the latest code with the fix in it.

**Comment by JohnnyUSA** [comment]
Yeah, saw it after i've replied here. Gonna try it and get back with results.

**Comment by JohnnyUSA** [comment]
```
[2018/01/23 01:05:56] upnpsoap.c:1533: warn: SQL error: near "order": syntax error
BAD SQL: SELECT o.OBJECT_ID, o.PARENT_ID, o.REF_ID, o.DETAIL_ID, o.CLASS, d.SIZE, d.TITLE, d.DURATION, d.BITRATE, d.SAMPLERATE, d.ARTIST, d.ALBUM, d.GENRE, d.COMMENT, d.CHANNELS, d.TRACK, d.DATE, d.RESOLUTION, d.THUMBNAIL, d.CREATOR, d.DLNA_PN, d.MIME, d.ALBUM_ART, d.ROTATION, d.DISC from OBJECTS o left join DETAILS d on (d.ID = o.DETAIL_ID) where (PARENT_ID = '0' and (o.password is null or o.password = '' or o.password in ('')) order by o.CLASS, d.TITLE)  limit 0, -1;
[2018/01/23 01:05:56] upnpsoap.c:123: warn: Returning UPnPError 709: Unsupported or invalid sort criteria
```
I've compiled the new version, same error.

Here is a picture that shows i have the current code with the fix that doesnt work:
https://postimg.org/image/b27mshjhn/

**Comment by NathanaelA** [comment]
This should be fixed in the latest release of the source code because I updated to v1.2.1 base.
