### ISSUE TITLE
Missing (git-ignored?) INSTALL file

### ISSUE THREAD

**Issue by vinzm** [NathanaelA/minidlna#11]
Hi everybody, I really appreciate your effort to introduce these features to minidlna.
Sorry to bothering you, but in the README file I can read:

> See the INSTALL file for instructions on compiling, installing, and configuring minidlna.

but I'm not able to find the INSTALL file — maybe it's because it's included in .gitignore?
Thanks again, regards.

**Comment by NathanaelA** [comment]
Thanks, I have created a brand new INSTALL file.   Apparently it never was in the original project, so nobody had one.
