### ISSUE TITLE
Password system not working ... and ERROR : minidlna.c:843: fatal: Failed to clean old file cache. EXITING

### ISSUE THREAD

**Issue by aiamuzz** [NathanaelA/minidlna#12]
I am getting the following error after i installed you password version on top of the original minidlna installation installed from my distro's repo ... (Linux Deepin(Debian based))

` minidlnad -R`

```
parsing error file /etc/minidlna.conf line 12 : password_length=4
parsing error file /etc/minidlna.conf line 66 : tivo_discovery=bonjour
rm: cannot remove '/var/cache/minidlna/files.db': Permission denied
rm: cannot remove '/var/cache/minidlna/art_cache': Permission denied
[2019/09/28 00:41:44] minidlna.c:843: fatal: Failed to clean old file cache. EXITING

```

**Comment by aiamuzz** [comment]
> parsing error file /etc/minidlna.conf line 66 : tivo_discovery=bonjour

I commented out the above line in the conf file and the error no longer showed ...

> rm: cannot remove '/var/cache/minidlna/files.db': Permission denied
> rm: cannot remove '/var/cache/minidlna/art_cache': Permission denied

I set the paths in the conf file to a directory on my home partition ... and the `minidlnad -R` is creating the necessary database files in that location and i am able to access the folders on my android tablet ... i am using BubbleUpNp app on my tablet ...

> parsing error file /etc/minidlna.conf line 12 : password_length=4

i un-commented the line for `password_length` and i am getting the above error ...

but when i comment out the line for `password_length` the error goes away but  i don't seem to have the password implementation working ... am i doing something wrong ... I followed all your installation instructions  ?

**Comment by aiamuzz** [comment]
I ran the command ... `sudo apt-get remove minidlna`

then i followed your installation instructions and installed using `sudo make install`

seems the executable `minidlnad -R' ... shows 

`bash: /sbin/minidlnad: No such file or directory
`

hmmmm ... need assistance to have this password feature up and running ...

**Comment by NathanaelA** [comment]
@aiamuzz - `sudo make install` -- installs it in `/usr/local/sbin`

**Comment by aiamuzz** [comment]
> @aiamuzz - `sudo make install` -- installs it in `/usr/local/sbin`

@NathanaelA ... thanks ... 

i ran `/usr/local/sbin/minidlnad -R` i was able to create the DB files ...

However I am not able to access the media ... besides the missing media files, i can see the dlna folders i have configured and **an additional folder name 'passwords'** ... 

How do i fix the issue where no media files are to be found ... the standard minidlna package i was able to access all the media ... but not on your package with the password feature ...

**Comment by NathanaelA** [comment]
1. You **DO NOT** want a folder called `passwords`  (This is a virtual folder that the interface creates).  :)
2. As long as your minidlna.conf file is configured for where your media is at; it should be publishing it.
3. You create any passwords inside of the `.password` file inside of the directory that you are trying to protect.

Any folders that do not have a `.password` file are treated just as normal minidlna does...

For example I run two instances of MiniDlna on my server for my `Learning` instance it is setup like this:
```
port=8201
network_interface=em1
media_dir=V,/DataDrive/Video/Video/Learning
friendly_name=Learning
db_dir=/DataDrive/Video/minidlna-learning
log_dir=/var/log/minidlna-learning
log_level=general=error,artwork,database,inotify,scanner,metadata,http=debug,ssd
album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt
inotify=yes
enable_tivo=no
strict_dlna=no
notify_interval=450
serial=23456789
model_number=2
uuid=ffddd2a1-e391-4fb6-bd7f-3e9548a90227
minissdpdsocket=/var/run/minissdpd2.sock
root_container=V
```

and starting it I call:
```
/usr/local/sbin/minidlnad -f /etc/minidlna-learning.conf -P /run/minidlna/minidlna-learning.pid
```

**Comment by aiamuzz** [comment]
> I run two instances of MiniDlna on my server for my `Learning` instance it is setup like this:

Oh wow can you do that ... run 2 instances of the dlna server ... how do you do that ... can you please guide me ... (after i am able to have your password feature up and running)

- I would love to have one instance of the server that will serve content only for me across my devices. !
- A second instance of the server for everybody else at home !

Can i do that ?

**Comment by aiamuzz** [comment]
> 3\. You create any passwords inside of the `.password` file inside of the directory that you are trying to protect.

This is exactly what i have done



> 1. You **DO NOT** want a folder called `passwords`  (This is a virtual folder that the interface creates).  :)

I have not created any folders with the name password ... if that is supposed to be a virtual folder then BubbleUpNp app is showing it as a physical folder.

I have uncommented the password length parameter ... should i be doing that ?



> 2\. As long as your minidlna.conf file is configured for where your media is at; it should be publishing it.

It is ... like i said ... if i install the minidlna package from my distributions repository on top of your installation then it will work and the media will show up as its supposed to ...

**Comment by aiamuzz** [comment]
This is my **miniclna.conf** file and its innards ...

```
port=8200
password_length=4
media_dir=PV,/home/muz/Downloads/TorrentDownloads/Downloaded/Movies
media_dir=PV,/home/muz/Downloads/TorrentDownloads/Downloaded/TV
media_dir=PV,/home/muz/Downloads
```
the above folders show up on my tablet ... the bottom set of folder paths don't ... do you know why that's happening ?

```
media_dir=PV,/home/muz/Videos/VideoTutorials
media_dir=PV,/media/muz/SoftwareRepository/TorrentsMedia/Movies
media_dir=PV,/media/muz/DeepinTestingVM/TorrentsMedia/VideoTuts/DeepinTestingVMSTORAGE
media_dir=PV,/media/muz/SoftwareRepository/TorrentsMedia/VideoTuts/SoftwareRepositorySTORAGE
media_dir=PV,/media/muz/STORAGE 7/TorrentsMedia/VideoTuts/STORAGE-7STORAGE
media_dir=PV,/media/muz/A My J/Torrents Media/VideoTuts/A-My-JSTORAGE
media_dir=PV,/media/muz/srcRepo/Torrents Media/Books/vidTuts/srcRepoSTORAGE
media_dir=PV,/media/muz/AI My J/Muzafshan Shariff/AIDEEN/Dr Israr Ahmed
media_dir=AV,/media/muz/A My J/16198114/Alhamdulillah Bayyinah
```

```
friendly_name=AMyDLNAServer
db_dir=/home/muz/.minidlna/database
log_dir=/home/muz/.minidlna/logs
```

the following are the defaults ... except for the `enable_tivo` setting
```
album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg
inotify=yes
enable_tivo=no
strict_dlna=no
notify_interval=900
serial=12345678
model_number=1
```

screenshots of the bubbleupnp app on my tab ...

![WhatsApp Image 2019-10-01 at 9 49 05 PM](https://user-images.githubusercontent.com/3283676/65980793-7a063d00-e495-11e9-92ba-e7b3481bb626.jpeg)
![WhatsApp Image 2019-10-01 at 9 49 07 PM](https://user-images.githubusercontent.com/3283676/65980805-7d99c400-e495-11e9-93fd-2885fbda9d65.jpeg)
![WhatsApp Image 2019-10-01 at 9 49 08 PM](https://user-images.githubusercontent.com/3283676/65980814-8094b480-e495-11e9-8e53-9396e62add24.jpeg)
![WhatsApp Image 2019-10-01 at 9 49 09 PM](https://user-images.githubusercontent.com/3283676/65980818-82f70e80-e495-11e9-96ff-568101dd565b.jpeg)


the 3 folders aren't showing any media ...
![WhatsApp Image 2019-10-01 at 9 49 11 PM](https://user-images.githubusercontent.com/3283676/65980881-a326cd80-e495-11e9-9b34-6538135ccd12.jpeg)
![WhatsApp Image 2019-10-01 at 9 49 13 PM](https://user-images.githubusercontent.com/3283676/65980884-a4f09100-e495-11e9-8762-3728f0c4725f.jpeg)
![WhatsApp Image 2019-10-01 at 9 49 15 PM](https://user-images.githubusercontent.com/3283676/65980887-a621be00-e495-11e9-8bf8-1b5b51ab8b3c.jpeg)

**Comment by NathanaelA** [comment]
You can run as many instances as you want.   The first line `port=xxxx` is how you set up additional instances.    

I run two; one is my "Learning" on that has just a huge number of different learning videos for everyone in the family to watch any time.   The second is actually locked down to be visible on only a couple devices; as I really don't want my kids watching lots of movies...  :)   

You need to make sure you have the minidlna config file setup; then it should work.   You can look at the logs it creates to see what it is failing on.

1. The MiniDLNA does create the "Password" folder; this allows you to put in a password.   Navigate the folders, and it will use each folder name as the next character of the password.      So if you created a `.password` file with the password "0123", you would navigate through the "Password", "0", "1", "2", "3".  Then you could go "Back" 5 times and go into the folder that should have those videos visible. 

2. I would first do a test without any .password files present.    Shutdown minidlna, Delete the `files.db` file then restart minidlna --  This way you can make sure the basic functionality works.   

3. Make sure the conf file it is loading actually has the correct path's to where your media is at.   If it doesn't it will be blank.

4. Make sure the minidlna user (if using the non-root user) has the rights to read the files in the media folder.

5. Check the logs; the logs will tell you what is going on...  :grinning:

**Comment by NathanaelA** [comment]
I just noticed part of your question: If you are missing folders  there are typically two reasons for this:
1. No security rights; so the user that is running minidlna doesn't have read rights to the folder.
2. The wrong conf file is being loaded.    

Checking the logs should give you a bit better of an idea which of those it is...

**Comment by aiamuzz** [comment]
@NathanaelA ...

thanks for the support ... like you advised i compiled and installed your password modified package ... and tried to get it working as a normal DLNA server (the password folder is there when viewed from BubbleUpNp on my android tab)

1. I commented the password length line in the config file...
2. I run the following commands 

`/usr/local/sbin/minidlnad -R -f /home/muz/.minidlna/minidlna.conf `

`sudo service minidlna restart`

I face the following issues ... If i remember right every time i make changes to the paths in the config file i need to run the above `minidlnad` command with the paths to the conf file ... When i do that ...

1. i can see that the database file keeps populating continuously ... it bloated to around 3.5 GB on my home folder
2. every time i run the above `minidlnad` command turns out a new instance of the `minidland` instance is started ... instance is a CPU hog and the multiple instances is choking my CPU at 100% slowing down/freezing my laptop. ... i thought the database files held only paths ... why is it populating continuously running in GigaByte's

3. response on my tab when trying to access through BubbleUpNp does not seem to be refreshing in realtime ... there is a lag ... even when i have stopped the service on my laptop the app on the tab still shows up the DLNA server ... it shouldn't see the server at all when its stopped isn't it ?

If the above issues can be ironed out ... i'd like to see your password implementation feature in action and also learn from you on running 2 servers ... one for open content and one for my video tutorials !!!

**Comment by aiamuzz** [comment]
after killing all instances of the `minidland` via the task manager ... i run the command afresh and i see 2 instances of `minidlnad` as you can see below ... 

![image](https://user-images.githubusercontent.com/3283676/66402020-c0155080-ea01-11e9-97c8-3b3c5c83796a.png)


is that normal ? Is it supposed to start 2 instances when starting afresh ? Also notice that one of that instance is hogging 10% of CPU bandwidth ... is it normal ? or is it some issue ?

![deepin-screen-recorder_Select area_20191008192951](https://user-images.githubusercontent.com/3283676/66402257-2ef2a980-ea02-11e9-93da-a474c59c00d5.gif)

As you can see above the database file populating growing continuosly ... its 60 MB and running ...
Is this normal ?

**Comment by aiamuzz** [comment]
while the database file is 781 MB and continue's to grow as i write this post ... i just noticed that the log file is also huge ... never have seen a simple text file so huge ...

![image](https://user-images.githubusercontent.com/3283676/66404903-e8537e00-ea06-11e9-91e0-f6561704bad3.png)
something seems seriously wrong with my setup

**Comment by aiamuzz** [comment]
ok ... the database file never stopped growing ... i just ended the 2 running instances of `minidlnad` via the task manager ... at the time of shutting down `minidlnad` the database file had populated/bloated to 6.1 GB and the Log file has grown to 523 MB ... I have deleted the database file to save space ... 

i haven't deleted the log file ... just in case you want me to post its contents ... but i am not very optimistic of being able to open such a huuuuuuuuuge text file ... i suspect it will crash my system  ... anyways, i have kept it so at least i can 'try'

@NathanaelA ... something seems seriously wrong with my setup ... need your help at resolving it !!!

**Comment by NathanaelA** [comment]
@aiamuzz - You are correct it does sound like something is messed up.     The normal minidlna with the same configuration works; but mine one doesn't.    Or are they using different configuration files?

You should be able to use any of several different file viewers to view the log.   I personally use midnight commander to view bigger log files; but their are several  of them that can page in text so you can view unlimited size files.
