### ISSUE TITLE
Issues with your package in comparison to the minidlna package from my repo ... (continuing from #12)

### ISSUE THREAD

**Issue by aiamuzz** [NathanaelA/minidlna#13]
@NathanaelA ... in continuation to our conversation from #12 ...

I thought i 'll open a new one with a fresh subject ...

from the last thread i ran `sudo make uninstall` and ran a `sudo apt-get install minidlna` from my repository ...

Observations of the generic version of minidlna from my repo ...

1. When i run the command `minidlnad -R -f ~/.minidlna/minidlna.conf` ... 2 instances of `minidlnad` is seen in the task manager as seen below ...

![image](https://user-images.githubusercontent.com/3283676/66484154-18ad2200-eac4-11e9-9d02-b549b9da1f0a.png)

this is only until the db files is populated ... after that only a single instance is seen running as seen below ...
![image](https://user-images.githubusercontent.com/3283676/66484206-2fec0f80-eac4-11e9-87be-d43843973db8.png)

Coming to the size of the db file from #12 ... the generic version of the package creates only 23.4 MB size of db file for my given configuration ... as can be seen below ...
![image](https://user-images.githubusercontent.com/3283676/66484309-5ad66380-eac4-11e9-851f-49e7c54cfde5.png)

and the log file too is a realistic size of ... a few KB as seen below ...

![image](https://user-images.githubusercontent.com/3283676/66485055-c1a84c80-eac5-11e9-8973-510ca4d3ede7.png)

If a make any changes to the `minidlna.conf` file i need to rerun the `minidlnad` command ... doing so only starts the second instance of the `minidlnad` ... but only until it populates the db file after that it returns to a single instance.

I am using 'MediaHouse DLNA client on my Android tab' ... i am able to access my media(video) files and play them on my tablet just fine.

Some anomalies (or maybe by design) ...

1. when i run the command `sudo service minidlna restart` after running the `minidlnad` command ... it seems to kill the minidlnad instance running shutting down the server ... no longer accessible ... but if i just let the `minidlnad` command without touching the minidlna service things go on smoothly ... is the `restart` command supposed to kill the server(instance of `minidlnad`) ???

2. As reported in #12 previously with this package complied and installed ... the ever growing db file running into GB's ... multiple instances of `minidilnad` after each time i make changes to the config file and run the `minidlnad` so the changes in the config file are effected ... no longer is occuring on the generic(orginal) minidlna package from the my repo ... except for the above 1. anomaly things are smooth and issueless.

**Comment by aiamuzz** [comment]
@NathanaelA ... so shall i uninstall the generic(original minidlna) package from my repo and rebuild and install your package from scratch the exact same lines as the above post ?

**Comment by aiamuzz** [comment]
@NathanaelA ... my observations of running this version(passwrod) of the package ...

1. Bloating db file issue ... returns on your package ... remember this is being run for the exact same copy of the config file ... a little less than 24 MB i the maximum size of the db file that should've been ... as you see below ... the db file size is way past twice the size of what should've been ...( i am sure it will continue to grow(as already reported in #12) until there is no longer any space left ... if i left it running long/overnight that is ...

![deepin-screen-recorder_Select area_20191009190411](https://user-images.githubusercontent.com/3283676/66486843-fb2e8700-eac8-11e9-9419-ff8609ea8205.gif)


2. The issue of multiple instances of minidlnad returns ...

multiple instances of `minidlnad` when i try running it when the first 2 instances were running ... as you can each instance of running the minidlnad command emulating a config edit is creating additional instance with 20-25% of CPU being hogged freezing and rendering my laptop unusable until i kill all the instances to liberate my possessed Laptop ... :smile: 

![image](https://user-images.githubusercontent.com/3283676/66486486-4d22dd00-eac8-11e9-81e8-21b7c6101143.png)

the only difference between the file browser is that your version has an addtional 'Passwords' folder besider the folders i have in my config file ... **the password system is not working though** ... i have the `.password` files with the password in them created inside the folders i want to protect ... but effectively the password feature isn't working ... (Note : the password length line in the config file is commented out ... should that be uncommented for the password feature to work ? or ... the presence of the `.password` file is enough for the password feature to function ?)

**Comment by aiamuzz** [comment]
If you wish to probe please find log files of both package versions ... generic(orginal) and your Password implementation package

[generic_version_minidlna.log](https://github.com/NathanaelA/minidlna/files/3707674/generic_version_minidlna.log)

[password_version_minidlna.log](https://github.com/NathanaelA/minidlna/files/3707673/password_version_minidlna.log)

**Comment by aiamuzz** [comment]
I tried building and installing at the following commit points ... with the hope of catching the point of issue through the package development path ...

https://github.com/NathanaelA/minidlna/commit/a0dd8695549f9c5cb2a622151b4562545fada686 - falied to `make`

https://github.com/NathanaelA/minidlna/commit/fe1d144aa972ecf0a9ab41cfddbc2f8b5b8f2ace - i could successfully install at this point of commit ... but the above reported issues persists even at this point of the package developement ...

**Comment by aiamuzz** [comment]
FYI ... the version supported on my repo is ... `1.1.6+dfsg-1 amd64`

**Comment by aiamuzz** [comment]
after extensive attempts at trying out various installs ... **i think the issue is with building and installing with `make`** ... which installs the executable at `/usr/local/sbin` ... 

@NathanaelA ... **Is there a way you can release a deb package installer for your variant ... which will install at the default location(@ `/sbin`) ?**

My repo has version 1.1.6 ... I had dependency issues with the direct version 1.2.1 ... however i could find a backport version which installs well on my system with its current package dependencies ... and this deb package installed version 1.2.1 seems to keep the db file at 23.4 MB ... and no over bloated never ending db file size anymore ...

PS : I tried building and installing 1.1.6 of the original `minidlna` from sourceforge and even that had the exact same issues i was facing with your variant ... as building from sources installs `minidlnad` at `/usr/local/sbin` ... hence my conclusion that the overbloated db file is as a result of running the executable from `/usr/local/sbin` location

**Comment by aiamuzz** [comment]
i am sorry ... i might be coming across as foolish ... but i am not a techie ... my observations are more of a layman observation ... 

A guess a more smarter(less foolish) question would be ... **Why is there different locations of installation(structure of installation) when we build and `make install` ... and ... when i install from my native repo or a deb package downloaded from debian packages ?**

**Comment by NathanaelA** [comment]
Each package format has a directories it puts different files.   MiniDLNA defaults to `/usr/local/sbin`   -- there is no difference to the OS if it was running in `/opt/minidlna` or any other folder.      When you run the `./configure` you can choose output directories.  (try running `./configure --help` to see the configuration options.
