### ISSUE TITLE
new files are visible

### ISSUE THREAD

**Issue by 532910** [NathanaelA/minidlna#14]
Steps to reproduce:
1. Start minidlna, wait for directory rescan.
2. Open DLNA browser (vlc for android in my case), don't enter password: it will show empty directory, as expected.
3. Add (copy) a new file into directory
4. Refresh DLNA browser: it will show a file above.

**Comment by NathanaelA** [comment]
Thanks for the report -- I'll have to test this..

**Comment by HeavenVolkoff** [comment]
I observed this same behavior in a deploy of this version of minidlna (Version: 1.2.1P). Currently I am running with inotify enabled and every new file added to a password protected directory become accessible to all users being them authenticated or not.
