### ISSUE TITLE
Problem on Samsung TV

### ISSUE THREAD

**Issue by immerx** [NathanaelA/minidlna#15]
A strange problem occurs on my Samsung TV: The depth of the Password directory is always one less than the password_length. 

For example, if the password length is set to 4 (default value) and the password is 1234, the depth of the Password directories is always 3, which means I can only enter directories 1->2->3, then the directory 3 is empty.

If I change the password_length to 3, the depth of the Password directory will be 2 on the TV, hence it is not possible to enter the correct password. 

On Android with VLC, everything is fine. Samsung uses something special?

**Comment by NathanaelA** [comment]
Hi that is interesting -- we can attempt to create some logging if you are willing to build it on your side for testing to see if we can figure out what is going on with the samsung device...

**Comment by immerx** [comment]
> Hi that is interesting -- we can attempt to create some logging if you are willing to build it on your side for testing to see if we can figure out what is going on with the samsung device...

Sure, I am glad to do some tests to figure it out. I checked the log file and there was nothing noticeable. What kinds of additional logging should we create?

**Comment by NathanaelA** [comment]
We can add some logging to out what state/level the password dialog is at -- maybe it is automatically entering the first level for you and so you are only seeing levels 1-3. (on 4 digits).    Basically we need to figure out why you are only seeing 3 of the 4 levels..

**Comment by NathanaelA** [comment]
I think if you uncomment this; and turn on debug http logging:
https://github.com/NathanaelA/minidlna/blob/master/upnpsoap.c#L1354
we should get the info we need...

**Comment by immerx** [comment]
I did the test and I paste the logs step by step in the following. 

After minidlnad starts, the log looked like:
>[2020/08/05 21:23:54] minidlna.c:200: warn: received signal 15, good-bye
[2020/08/05 21:23:57] minidlna.c:1132: warn: Starting MiniDLNA version 1.2.1P.
[2020/08/05 21:23:57] minidlna.c:1192: warn: HTTP listening on port 8200
[2020/08/05 21:23:57] monitor.c:223: warn: WARNING: Inotify max_user_watches [8192] is low or close to the num
ber of used watches [16] and I do not have permission to increase this limit.  Please do so manually by writin
g a higher value into /proc/sys/fs/inotify/max_user_watches.

I connected the server on the Samsung TV and opened the Password directory, it showed directory 1-10 and the following added in the log:
>[2020/08/05 21:25:09] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32
> * Parent: 0
> * Start: 2/3
> * Depth: 0
> * isMeta: 1
>[2020/08/05 21:25:09] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32
> * Parent: 32
> * Start: 0/10
> * Depth: 0
> * isMeta: 0
>[2020/08/05 21:25:09] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32
> * Parent: 0
> * Start: 2/3
> * Depth: 0
> * isMeta: 1
>[2020/08/05 21:25:09] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32
> * Parent: 32
> * Start: 0/10
> * Depth: 0
> * isMeta: 0

Then I opened the directory 1, it showed directory 1-10 and the following added in the log:
>[2020/08/05 21:25:39] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1
> * Parent: 32
> * Start: 1/2
> * Depth: 1
> * isMeta: 1
>[2020/08/05 21:25:39] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1
> * Parent: 32$1
> * Start: 0/10
> * Depth: 1
> * isMeta: 0
>[2020/08/05 21:25:39] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1
> * Parent: 32
> * Start: 1/2
> * Depth: 1
> * isMeta: 1
>[2020/08/05 21:25:40] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1
> * Parent: 32$1
> * Start: 0/10
> * Depth: 1
> * isMeta: 0

Then I opened the directory 2, it showed directory 1-10 and the following added in the log:
>[2020/08/05 21:26:10] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1$2
> * Parent: 32$1
> * Start: 2/3
> * Depth: 2
> * isMeta: 1
>[2020/08/05 21:26:10] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1$2
> * Parent: 32$1
> * Start: 2/3
> * Depth: 2
> * isMeta: 1
>[2020/08/05 21:26:10] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1$2
> * Parent: 32$1$2
> * Start: 0/10
> * Depth: 2
> * isMeta: 0
>[2020/08/05 21:26:10] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1$2
> * Parent: 32$1$2
> * Start: 0/10
> * Depth: 2
> * isMeta: 0

Then I opened the directory 3, it's empty and the following added in the log (This time only TWO logs instead of four):
>[2020/08/05 21:26:21] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1$2$3
> * Parent: 32$1$2
> * Start: 3/4
> * Depth: 3
> * isMeta: 1
>[2020/08/05 21:26:21] upnpsoap.c:1360: warn: Generating Password Set:
> * ObjectID: 32$1$2$3
> * Parent: 32$1$2
> * Start: 3/4
> * Depth: 3
> * isMeta: 1

Does it shed some light? (Btw, I changed the log level to E_WARN in order to output the log.)

**Comment by NathanaelA** [comment]
@immerx - Sorry for the long delay; I didn't see that you responded.  If you are still interested in trying to resolve this -- we can attempt to add some additional logging to see if we can figure out why.   The path's do look correct.

**Comment by photonq2** [comment]
Hi, Im interested in helping here. Same issue.

**Comment by reboost** [comment]
@NathanaelA I also had the same issue, and after fixing it to get to last folder, I wasn't able to unlock protected folders after entering the correct password and I had empty protected folders. My pull request e40803540c091b09c15b6fe76946704acea07104 fixes all password issues for my Samsung TV. Thank you!
