### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by bkev** [NathanaelA/minidlna#17]
Hi,
I've been using your version of minidlna for a while and it's great!
I have noticed that my log file is quite large though and it is full of these messages
minissdp.c:315: error: sendto(udp_notify=9, xx.xxx.xx.xx): Required key not available

Do I need to add this IP address into the config somewhere? 

I'm unsure what this means I'm afraid. 

Thanks again for this software.

**Comment by NathanaelA** [comment]
This error appears to be just when it is talking to your device.  Your device isn't sending some info back, so it is complaining about it.
