### ISSUE TITLE
Newbie installations

### ISSUE THREAD

**Issue by JoaoLeaoO** [NathanaelA/minidlna#9]
Hey there, I appreciate the effort to make these changes to minidlna. i wish to make those on my own but i'm a total newbie on these matters, as i'm no programmer. 

I do not wish to bother, so if its impossible or unwilling to cooperate delete this or just ignore it please.

The deal is i've used this software on my raspberry pi 3 for years now and i wish to use password to some files due to multiple users on my home. 
as this seems to be the only place people ever discuss this, it got my hopes up.

so heres my request, if possible please do a walkthrough, thank you for the attention!

**Comment by chriswyatt** [comment]
Hi JoaoLeaoO,

I'm not a developer here, and I'm no expert on DLNA, but you could perhaps look into IP whitelisting. It's not very secure, and also relies on static IPs (or manually changing whenever the DHCP server assigns a new IP), but it's something to consider.

https://www.garron.me/en/bits/iptables-open-port-for-specific-ip.html

**Comment by NathanaelA** [comment]
White listing is a cool feature idea.  (And I still use this!)

**Comment by chriswyatt** [comment]
I'd also find this feature useful :). I was using PS3 Media Server (which has an IP whitelisting feature), but that project seems to have died, so I've returned to minidlna.

Thanks for continuing to support this.

**Comment by NathanaelA** [comment]
Just as a FYI, the `INSTALL.MD` file has newbie instructions.   I forgot to post that I added it a while back, so if people see this issue in the future...
